repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0   # versione stabile
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1   # versione stabile
    hooks:
      - id: nbstripout
